# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('add_time', models.DateTimeField(verbose_name='发布时间')),
                ('char_size', models.IntegerField(verbose_name='字数')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 't_chapter',
                'ordering': ['add_time'],
            },
        ),
        migrations.CreateModel(
            name='VolumeSetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='卷名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.BookModel', verbose_name='所属书')),
            ],
            options={
                'verbose_name': '卷集',
                'verbose_name_plural': '卷集',
                'db_table': 't_volume',
                'ordering': ['add_time'],
            },
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.VolumeSetModel'),
        ),
    ]
