# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20180920_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间'),
        ),
    ]
